services:
  postgres:
    container_name: postgres-sql-portfolio
    image: postgres:16.0
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_portfolio
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net-portfolio
    restart: unless-stopped

networks:
  net-portfolio:
    driver: bridge

volumes:
  postgres:
    driver: local
